name: 'My reusable action'
description: 'This is a reusable action'
runs:
  using: 'composite'

  steps:
    - name: 设置文件夹名为环境变量
      run: |
        directories=""
        for dir in $(ls -d */); do
          directories="$directories ${dir%/}"
        done
        echo "DIRECTORY_NAMES=$directories" >> $GITHUB_ENV
      shell: bash

    - name: 安装依赖和构建
      run: |
        IFS=' ' read -r -a array <<< "$DIRECTORY_NAMES"
        index=$((10#$MESSAGE-1))
        cd "${array[$index]}"
        npm install
        npm run build
        echo "$index"
        if [ $index -eq 13  ]
        then
          echo "构建backend"
          cd backend
          npm install
          npm run build
        fi
        if [ $index -eq 16 ]
        then
          cd ../backend
          npm install
          npm run build
        fi
      shell: bash

    - name: 部署 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{env.MESSAGE}}-build
        folder: ${{env.MESSAGE}}-build
    - name: 上传
      uses: actions/upload-artifact@v4
      with:
          name: ${{env.MESSAGE}}-build
          path: ${{env.MESSAGE}}-build


